#!/usr/bin/env sh

echo "Pre-commit hook in action ..."

chmod +x scripts/run-tests.sh
scripts/run-tests.sh

# Check if the exit value of last command
if [ "$mycmd" -ne 0 ]; then
 echo "Tests failed!"
 exit 1
fi